name: suitmedia_testportal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  iconly: any
  provider: any
  google_fonts: any
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/btn_add_photo.png
